package card;

public enum GameType { 
	HOLDEM, 
	OMAHA_HIGH, 
	OMAHA_HILO, 
	SEVENSTUD_HIGH, 
	SEVENSTUD_HILOW, 
	RAZZ, 
	DEUCE_TO_SEVEN_TRIPLEDRAW, 
	DEUCE_TO_SEVEN_SINGLEDRAW, 
	FIVECARD_TRIPLEDRAW, 
	FIVECARD_SINGLEDRAW 
}
